//TwitterApp Component
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//Login Component
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const UPDATE_LOGIN_FORM_REQUEST = "UPDATE_LOGIN_FORM_REQUEST"

//Signup Component
export const SIGNUP_RESULT_FAIL = 'SIGNUP_RESULT_FAIL'
export const VALIDATE_USER_RESPONSE = 'VALIDATE_USER_RESPONSE'
export const UPDATE_SIGNUP_FORM_REQUEST = 'UPDATE_SIGNUP_FORM_REQUEST'

//TweetsContainer Component
export const LOAD_TWEETS = 'LOAD_TWEETS'
export const ADD_NEW_TWEET_SUCCESS = 'ADD_NEW_TWEET_SUCCESS'

//Tweet Component
export const LIKE_TWEET_REQUEST = 'LIKE_TWEET_REQUEST'
export const LIKE_TWEET_DETAIL_REQUEST = 'LIKE_TWEET_DETAIL_REQUEST'

//Reply Component
export const UPDATE_REPLY_FORM = 'UPDATE_REPLY_FORM'
export const RESET_REPLY_FORM = 'RESET_REPLY_FORM'

//SuggestedUser Component
export const LOAD_SUGESTED_USERS = 'LOAD_SUGESTED_USERS'

//Toolbar Component
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

//Followers & Folliwings Components
export const FIND_FOLLOWERS_FOLLOWINGS_REQUEST = 'FIND_FOLLOWERS_FOLLOWINGS_REQUEST'
export const RESET_FOLLOWERS_FOLLOWINGS_REQUEST = 'RESET_FOLLOWERS_FOLLOWINGS_REQUEST'

//UserPage Component
export const USER_PAGE_FOLLOW_USER = 'USER_PAGE_FOLLOW_USER'
export const USER_PAGE_SAVE_CHANGES = 'USER_PAGE_SAVE_CHANGES'
export const USER_PAGE_AVATAR_UPDATE = 'USER_PAGE_AVATAR_UPDATE'
export const USER_PAGE_BANNER_UPDATE = 'USER_PAGE_BANNER_UPDATE'
export const UPDATE_USER_PAGE_FORM_REQUEST = 'UPDATE_USER_PAGE_FORM_REQUEST'
export const CANCEL_EDIT_MODEL_REQUEST = 'CANCEL_EDIT_MODEL_REQUEST'
export const CHANGE_TO_EDIT_MODE_REQUEST = 'CHANGE_TO_EDIT_MODE_REQUEST'
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'

//TweetDetails Component
export const ADD_NEW_TWEET_REPLY = 'ADD_NEW_TWEET_REPLY'
export const LOAD_TWEET_DETAIL = 'LOAD_TWEET_DETAIL'
