// UserPage
export const USERPAGE_RESET = 'USERPAGE_RESET'
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE'
export const LOAD_USERPROFILE = 'LOAD_USERPROFILE'
export const LOAD_FOLLOWERS = 'LOAD_FOLLOWERS'
export const LOAD_FOLLOWINGS = 'LOAD_FOLLOWINGS'
export const FOLLOW_USER = 'FOLLOW_USER'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const SAVE_PROFILE = 'SAVE_PROFILE'

// Tweets
export const RESET_TWEETS = 'RESET_TWEETS'
export const LOAD_TWEETS = 'LOAD_TWEETS'
export const ADD_NEW_TWEET = 'ADD_NEW_TWEET'
export const LIKE_TWEET_REQUEST = 'LIKE_TWEET_REQUEST'